project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 4: Visualising Distribution"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04(1).html"
        - text: "Hands-on Exercise 4: Visual Statistical Analysis"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04(2).html"
        - text: "Hands-on Exercise 4: Visualising Uncertainty"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04(3).html"
        - text: "Hands-on Exercise 4: Building Funnel Plot with R"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04(4).html"
        - text: "Hands-on Exercise 5"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
        - text: "Hands-on Exercise 6"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
    - text: "Take-home Exercise"
      menu: 
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take-home Exercise 2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

